### ISSUE TITLE
Support external graphql schema to be referenced

### ISSUE THREAD

**Issue by Swazimodo** [FWDSEC/burp-auto-gql#4]
Our companies policy is to turn off introspection in production but sometimes you can still get the schema in other ways. It would be useful to be able to upload the schema if it was available. The extension could then use this to generate the queries.

**Comment by falasi** [comment]
@Swazimodo I added an optional text field and functionality that loads the introspection schema.json from a file locally. I submitted via pull request and hope it gets added. If not have a look at my forked version.

**Comment by jmeit-fwdsec** [comment]
This has now been merged. Very happy to finally have this feature available. Big ups to @falasi !
Relevant PR: https://github.com/FWDSEC/burp-auto-gql/pull/5
